name: release

on:
  schedule:
  - cron: '0 18 * * *'
  push:
    branches: [ master, test ]
  workflow_dispatch:

env:
  llvm_ver: 12.0.1
  ninja_ver: 1.10.2

jobs:
  ubuntu2004:
    runs-on: ubuntu-20.04
    outputs:
      winscp_ver: ${{ steps.winscp.outputs.version }}
      putty_ver: ${{ steps.putty.outputs.version }}
      mobaxterm_ver: ${{ steps.mobaxterm.outputs.version }}
      tig_ver: ${{ steps.tig.outputs.version }}
    steps:
      - name: Install xmake
        run: |
          mkdir -p ~/tools

          ver=$(curl -sv "https://github.com/xmake-io/xmake/releases/latest" 2>&1 | grep -P location: | grep -Po "(\d+\.){2}\d+")
          wget -qOxmake.deb https://github.com/xmake-io/xmake/releases/download/v$ver/xmake-v$ver.amd64.deb
          sudo dpkg -i xmake.deb
          xmake --version

      - name: Build ctags
        id: ctags
        run: |
          sudo apt-get update
          sudo apt-get install -y locales-all

          echo "install libxml2"
          wget -qOlibxml2.tgz https://github.com/GNOME/libxml2/archive/refs/tags/v2.9.12.tar.gz
          tar xzf libxml2.tgz
          cd libxml2-*
          xmake f --trybuild=autotools --tryconfigs="--prefix=/usr/local \
                  --sysconfdir=/etc --localstatedir=/var --runstatedir=/run \
                  --disable-option-checking --disable-silent-rules --disable-maintainer-mode --disable-dependency-tracking"
          sudo xmake --root

          echo "build ctags"
          git clone https://github.com/universal-ctags/ctags
          cd ctags
          xmake f --trybuild=autotools --tryconfigs="--enable-static" --cxflags="-s -Os"
          xmake
          cp build/artifacts/bin/ctags .
          chmod a+x ./ctags
          ./ctags --version
          ldd ./ctags || true
          XZ_OPT=-9 tar cJvf ~/tools/ctags_linux_amd64.txz ctags

      - name: Build tig
        id: tig
        run: |
          echo "install ncursesw"
          # https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.3.tar.gz
          wget -qOncurses.tgz https://mirrors.aliyun.com/gnu/ncurses/ncurses-6.3.tar.gz
          tar xzf ncurses.tgz
          cd ncurses-*
          xmake f --trybuild=autotools --tryconfigs="--prefix=/usr/local \
                  --enable-widec --enable-pc-files --with-terminfo-dirs='/etc/terminfo:/lib/terminfo:/usr/share/terminfo' \
                  --without-debug --without-tests"
          sudo xmake --root
          cd -

          echo "install readline"
          # https://ftp.gnu.org/gnu/readline/readline-8.1.tar.gz
          wget -qOreadline.tgz https://mirrors.aliyun.com/gnu/readline/readline-8.1.tar.gz
          tar xzf readline.tgz
          cd readline-*
          xmake f --trybuild=autotools --tryconfigs="--prefix=/usr/local"
          sudo xmake --root
          cd -

          echo "install pcre2"
          wget -qOpcre2.tgz https://jaist.dl.sourceforge.net/project/pcre/pcre2/10.37/pcre2-10.37.tar.gz
          tar xzf pcre2.tgz
          cd pcre2-*
          xmake f --trybuild=autotools --tryconfigs="--prefix=/usr/local \
              --build=x86_64-linux-gnu --sysconfdir=/etc --localstatedir=/var \
              --disable-option-checking --disable-silent-rules \
              --disable-maintainer-mode --disable-dependency-tracking --enable-pcre2-16 --enable-pcre2-32 \
              --disable-pcre2grep-callout"
          sudo xmake --root
          cd -

          echo "build tig"
          ver=$(curl -sv "https://github.com/jonas/tig/releases/latest" 2>&1 | grep -P location: | grep -Po "(\d+\.){2}\d+")
          #ver=2.5.4
          wget -qOtig.tgz https://github.com/jonas/tig/releases/download/tig-$ver/tig-$ver.tar.gz
          tar xzf tig.tgz
          cd tig-*
          xmake f --trybuild=autotools --cxflags="-I/usr/local/include" --ldflags="-static -L/usr/local/lib"
          xmake
          cp build/artifacts/bin/tig .
          chmod a+x ./tig
          ./tig --version
          ldd ./tig || true
          XZ_OPT=-9 tar cJvf ~/tools/tig_linux_amd64.txz tig
          echo "::set-output name=version::$ver"

      - name: Get putty
        id: putty
        run: |
          ver=$(curl -s "https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html" | grep -Po "(?<=latest release \()\d\.\d+" | head -1)
          mkdir -p putty && cd $_
          wget -q https://the.earth.li/~sgtatham/putty/latest/w64/putty.exe
          wget -q https://the.earth.li/~sgtatham/putty/latest/w64/pscp.exe
          wget -q https://the.earth.li/~sgtatham/putty/latest/w64/psftp.exe
          wget -q https://the.earth.li/~sgtatham/putty/latest/w64/puttytel.exe
          wget -q https://the.earth.li/~sgtatham/putty/latest/w64/plink.exe
          wget -q https://the.earth.li/~sgtatham/putty/latest/w64/pageant.exe
          wget -q https://the.earth.li/~sgtatham/putty/latest/w64/puttygen.exe
          7z -mx9 a ~/tools/putty_${ver}.zip ../putty
          echo "::set-output name=version::$ver"

      - name: Get MobaXterm
        id: mobaxterm
        run: |
          moba_link=$(curl -s https://mobaxterm.mobatek.net/download-home-edition.html | grep -Po "https:.*?Portable.*?\.zip" | head -1)
          ver=$(echo $moba_link | grep -Po "\d+\.\d+")
          wget -q $moba_link
          7z x MobaXterm*.zip -oMobaXterm
          mv MobaXterm/MobaXterm* MobaXterm/MobaXterm.exe
          7z -mx9 a ~/tools/MobaXterm_${ver}.zip ./MobaXterm
          echo "::set-output name=version::$ver"

      - name: Get winscp
        id: winscp
        run: |
          ver=$(curl -s "https://github.com/winscp/winscp/tags" | grep -Po "(?<=tags/)(\d+\.){2}\d+(?=\.zip)" | head -1)
          mkdir -p winscp && cd $_
          wget -qOwinscp.zip https://jaist.dl.sourceforge.net/project/winscp/WinSCP/${ver}/WinSCP-${ver}-Portable.zip
          unzip winscp.zip && rm winscp.zip
          7z -mx9 a ~/tools/winscp_${ver}.zip ../winscp
          echo "::set-output name=version::$ver"

      - uses: actions/upload-artifact@v2
        with:
          name: tools
          path: ~/tools
          retention-days: 1

  clangd:
    runs-on: ubuntu-20.04
    outputs:
      clangd_ver: ${{ steps.clangd.outputs.version }}
    steps:
      - name: Init env
        run: |
          mkdir -p ~/tools

          wget -qOninja.zip https://github.com/ninja-build/ninja/releases/download/v${ninja_ver}/ninja-linux.zip
          7z x ninja.zip
          sudo mv ninja /usr/local/bin
          ninja --version

          sudo apt-get update
          sudo apt-get install -y libz-dev libc-ares-dev
          clang++ --version

      - name: Build clangd with rpath
        id: clangd
        run: |
          #ver=$(curl -s "https://github.com/llvm/llvm-project/releases/latest" | grep -Po "(\d+\.){2}\d+")
          #src_link="https://github.com/llvm/llvm-project/releases/download/llvmorg-$ver/llvm-project-$ver.src.tar.xz"
          #wget -qOllvm.txz $src_link
          #tar xJf llvm.txz
          #cd llvm-project-*

          git clone https://github.com/llvm/llvm-project --depth 1
          cd llvm-project

          cmake -S llvm -B Release -G Ninja \
                -DLLVM_TARGETS_TO_BUILD="X86" \
                -DCMAKE_BUILD_TYPE=Release \
                -DLLVM_ENABLE_ASSERTIONS=OFF \
                -DLLVM_ENABLE_BACKTRACES=ON \
                -DLLVM_ENABLE_TERMINFO=OFF \
                -DCLANG_PLUGIN_SUPPORT=OFF \
                -DLLVM_ENABLE_PLUGINS=OFF \
                -DLLVM_STATIC_LINK_CXX_STDLIB=ON \
                -DLLVM_ENABLE_ZLIB=OFF \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
                -DCMAKE_C_FLAGS_RELEASE="-gline-tables-only -DNDEBUG -Os" \
                -DCMAKE_CXX_FLAGS_RELEASE="-gline-tables-only -DNDEBUG -Os" \
                -DCMAKE_EXE_LINKER_FLAGS_RELEASE="-static-libgcc -Wl,-s -Wl,-rpath=."

          ninja -C Release clangd
          ldd Release/bin/clangd && du -h $_ && chmod +x $_

          mkdir -p bin lib/clang
          mv Release/bin/clangd lib/clang/
          ldd lib/clang/clangd | grep -Po "/lib/x86.*\.so\.\d+" | xargs -i cp -v {} lib/clang/
          ldd lib/clang/clangd | grep -Po "/lib64/ld-linux.*\.so\.\d+" | xargs -i cp -v {} lib/clang/ld.so
          {
            echo "#!/usr/bin/env bash"
            echo 'cd "$(dirname $0)/../lib/clang"'
            echo 'exec ./ld.so ./clangd $@'
          } > bin/clangd
          chmod +x bin/clangd

          ver=$(./bin/clangd --version | grep -Po "\d+\.\d+\.\d+")
          echo "::set-output name=version::$ver"

          mkdir clangd_$ver && mv bin lib $_
          XZ_OPT=-9 tar cJvf ~/tools/clangd_linux_amd64.txz clangd_$ver
      - uses: actions/upload-artifact@v2
        with:
          name: tools
          path: ~/tools
          retention-days: 1

  ccls:
    runs-on: ubuntu-20.04
    steps:
      - name: Download llvm
        run: |
          mkdir -p ~/tools
          wget -qOllvm.tar.xz "https://github.com/llvm/llvm-project/releases/download/llvmorg-${llvm_ver}/clang+llvm-${llvm_ver}-x86_64-linux-gnu-ubuntu-16.04.tar.xz"
          tar xJf llvm.tar.xz
          pwd && ls
          mv clang* llvm
      - name: Download ccls
        run: |
          wget -qOninja.zip https://github.com/ninja-build/ninja/releases/download/v${ninja_ver}/ninja-linux.zip
          7z x ninja.zip
          sudo mv ninja /usr/local/bin
          ninja --version

          cat /proc/cpuinfo | grep processor
          cmake --version
          g++ --version
          git clone --recursive https://github.com/MaskRay/ccls
      - name: Build ccls
        run: |
          cd ccls

          # /usr/bin/ld: cannot find -lgcc_s
          sed 's/project(ccls LANGUAGES CXX C)/project(ccls LANGUAGES CXX)/' -i CMakeLists.txt

          #cmake -S. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=../llvm -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++"
          cmake -S. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=../llvm -DCMAKE_CXX_FLAGS="-static -pthread -lrt -ldl -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -Os -s -flto"
          ninja -C Release

          mv Release/ccls .
          chmod a+x ./ccls
          ./ccls --version
          ldd ./ccls || true
          XZ_OPT=-9 tar cJvf ~/tools/ccls_linux_amd64.txz ccls
      - uses: actions/upload-artifact@v2
        with:
          name: tools
          path: ~/tools
          retention-days: 1

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Download llvm
        run: |
          cd /d c:\
          curl -L -ollvm.7z https://github.com/fcying/tools/releases/download/llvm-v${{ env.llvm_ver }}/llvm_msvc.7z
          7z x llvm.7z
          dir
      - name: Build ccls
        run: |
          git clone --depth=1 --recursive https://github.com/MaskRay/ccls
          cd ccls
          cmake -H. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_PREFIX_PATH="c:/llvm/Release"
          ninja -C Release

          .\Release\ccls.exe --version
          mkdir ccls
          copy Release\ccls.exe .\ccls\
          copy c:\Windows\System32\vcruntime140_1.dll .\ccls\
          copy c:\Windows\System32\vcruntime140.dll .\ccls\
          copy c:\Windows\System32\msvcp140.dll .\ccls\

          7z -mx9 a ..\ccls_windows_amd64.zip ccls
      - uses: actions/upload-artifact@v2
        with:
          name: tools
          path: ./ccls_windows_amd64.zip
          retention-days: 1

  publish:
    #needs: [ubuntu2004]
    needs: [ubuntu2004, clangd, ccls, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Download data
        run: ls -la

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITEE_KEY: ${{ secrets.GITEE_KEY }}
        run: |
          {
            echo "* clangd ${{ needs.clangd.outputs.clangd_ver }} nightly with rpath lib"
            echo "* ccls nightly static"
            echo "build with llvm ${{ env.llvm_ver }}"
            echo "* putty ${{ needs.ubuntu2004.outputs.putty_ver }}"
            echo "* MobaXterm ${{ needs.ubuntu2004.outputs.mobaxterm_ver }}"
            echo "* winscp ${{ needs.ubuntu2004.outputs.winscp_ver }}"
            echo "* tig ${{ needs.ubuntu2004.outputs.tig_ver }} static"
            echo "* ctags nightly static"
          } | tee /tmp/note.md
          gh release delete tools -y || true
          git push origin :tools || true
          gh release create tools -t "tools" -F "/tmp/note.md" --target $GITHUB_SHA ./tools/*

          ## push to gitee
          #mkdir -p ~/.ssh
          #chmod 700 ~/.ssh
          #eval $(ssh-agent)
          #echo "$GITEE_KEY" | ssh-add -
          #ssh-keyscan -t ed25519 gitee.com >> ~/.ssh/known_hosts
          #
          #git config --global user.name "fcying"
          #git config --global user.email "fcyingmk2@gmail.com"
          #
          #git clone -v git@gitee.com:fcying/tools.git gitee
          #cd gitee
          #git reset --hard init
          #
          #cp ../tools/* .
          #git add .
          #git commit -m "add release"
          #
          #git reflog expire --expire-unreachable=now --all
          #git gc --prune=now
          #
          #git push --force --all
          #
          ## clean
          #ssh-add -D
          #eval $(ssh-agent -k)

